spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${AUTH_CLIENT_ID}
            client-secret: ${AUTH_SECRET}
            authorization-grant-type: ${AUTH_GRANT}
        provider:
          keycloak:
            token-uri: ${AUTH_TOKEN_URI}

