version: '3.7'
services:
  discovery:
    build: ./discovery
    ports:
      - 9003:9003
    env_file:
      - mobilemoney.env
    restart: on-failure

  config:
    build: ./config
    ports:
    - 9000:9000
    env_file:
      - config/config.env
    depends_on:
      - discovery
    restart: on-failure

  gateway:
    build:
      ./gateway
    ports:
    - 9002:9002
    env_file:
      - mobilemoney.env
    depends_on:
      - discovery
      - config
      - keycloak
    restart: on-failure

  donne:
    build: ./donne
    ports:
    - 9001:9001
    env_file:
      - donne/donne.env
    depends_on:
      - discovery
      - config
      - keycloak
      - dbmobilepaiement

  mobilepaiement:
    build: ./mobilepaiement
    ports:
      - 9004:9004
    env_file:
      - mobilepaiement/mobilepaiement.env
    depends_on:
      - config
      - discovery
      - donne

  backoffice:
    build: ./backoffice
    ports:
      - 9080:80
    environment:
      - env=prod
    depends_on:
      - gateway

  smsserver:
    build: ./smsserver
    ports:
      - 9006:9006
    env_file:
      - smsserver/smsserver.env
    depends_on:
      - config
      - donne
      - discovery


  #utility
  dbmobilepaiement:
    image: "postgres" # use latest official postgres version
    ports:
      - 9054:5432
    env_file:
      - database.env
    volumes:
      - ./dbinitKeycloak.sql:/docker-entrypoint-initdb.d/init.sql
      - database-data=/var/lib/postgresql/data/
    restart: on-failure

  keycloak:
    image: jboss/keycloak:latest
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    #volumes:
    #  - ./config:/config/
    env_file:
      - keycloak.env
    ports:
      - "9007:8080"
    depends_on:
      - dbmobilepaiement
    restart: on-failure

  sut:
    image: alpine
    volumes:
      - ./run_tests.sh: /home/
    entrypoint: "sh /home/run_tests.sh"
    depends_on:
      - donne
      - gateway
      - backoffice
      - smsserver
