spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${AUTH_CLIENT_ID:mobilepaiement}
            client-secret: ${AUTH_SECRET:c7c35d1c-1534-4a29-895b-3a4a5eceb199}
            authorization-grant-type: ${AUTH_GRANT:client_credentials}
        provider:
          keycloak:
            token-uri: ${AUTH_TOKEN_URI:http://192.168.43.84:9007/auth/realms/mobilepaiement/protocol/openid-connect/token}

