spring:
  cloud:
    gateway:
      routes:
        - id: donne
          uri: lb://DONNE
          predicates:
            - Path=/donne/**
          filters:
            - RewritePath=/donne/(?<segment>.*), /$\{segment}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${AUTH_URI}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${AUTH_CLIENT_ID:mobilepaiement}
            client-secret: ${AUTH_SECRET}
